### ISSUE TITLE
MultiPeerConnectivity Feature

### ISSUE THREAD

**Issue by dehlen** [rakutentech/macos-push-tester#17]
Hey, 
first of all thank you very much for making this Open Source and providing such a great tool. I was wondering how the MultiPeerConnectivity feature is supposed to work. Does the app which is tested need to implement the framework as well in order to make it visible in the "Find Devices" section of your app? I tried to get my iPhone to show up in this list but had no luck so far. What is needed to make this feature work?

Thanks,
David

**Comment by dehlen** [comment]
Nevermind I just had a look at the Readme.... Thanks for documenting 👍

**Comment by malayli** [comment]
Hello David @dehlen ,

Did it work for you?

If you use cocoapods, you can also add this pod to your iOS app Podfile:

https://github.com/malayli/ios-device-advertiser

**Comment by dehlen** [comment]
Yes It works as advertised 😉
I just did not see the entry in your readme at first when scanning the repository. The pod makes the integration pretty seamless, thanks :)

**Comment by malayli** [comment]
Glad to know that! :D @dehlen
